### PR TITLE
Added missing newline at end of file

### PR DESCRIPTION
**Pull request by woodb**
Nothing too interesting here, I had just noticed that many of the event files did not terminate in a line break, which is not compliant with [ANSI C ](http://www.open-std.org/JTC1/SC22/WG14/www/docs/n1570.pdf) (5.1.1.2) or POSIX, etc.

This pull request adds a line break to all files that are missing one at the end.

### CODE REVIEW

**Comment by tturocy** [comment]
Retrosheet files are definitely not consistently formatted in terms of these niceties - an artefact of them being largely Windows-based.

This is a useful idea, but I did notice a lot of the files were fixed by adding a full blank line rather than just a newline.  That might cause problems with some users' parsing codes.

**Comment by woodb** [comment]
> I did notice a lot of the files were fixed by adding a full blank line rather than just a newline

Good catch. I'll double check and (force) push an update to this branch.

**Comment by woodb** [comment]
I've updated this PR to reflect the discussion above, and double checked/hand fixed any of the pesky newlines that got added as well. We're ready for review again.

I've left this as 3 commits because of https://github.com/chadwickbureau/retrosheet/pull/8/commits/1edb63f4673c64628c4ac7f5f95b6783231f587a. I noticed during this effort that there were a handful of files that contained `^Z` at the end and did some digging/asking around... turns out it's an old end-of-line character that used to be used in MS-DOS.

Because these characters were present in only handful of files, I figured we could make this consistent, too, by removing these characters. They were also partially to blame for adding the errant newlines to certain files. I've added more information about this [in the commit message](https://github.com/chadwickbureau/retrosheet/pull/8/commits/1edb63f4673c64628c4ac7f5f95b6783231f587a).

If PR commits are typically squashed to a single commit prior to merging, I'll be happy to squash/force push that up. Just wanted to make it easier to review in the interim.

**Comment by tturocy** [comment]
Looks reasonable, and it's reasonable to leave them as separate commits.  Merged with thanks.

**Pull request merged**
